sudo: required
services:
  - docker

before_install:
  - docker build -t docker1200/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker1200/react-test npm test

after_success:
  - docker build -t docker1200/multi-client ./client
  - docker build -t docker1200/multi-nginx ./nginx
  - docker build -t docker1200/multi-server ./server
  - docker build -t docker1200/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push docker1200/multi-client
  - docker push docker1200/multi-nginx
  - docker push docker1200/multi-server
  - docker push docker1200/multi-worker